In [5]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
print(a)

[[1 2 3 4]
 [2 3 4 5]]


In [11]:
import numpy as np
a=np.zeros((4,3))
print("the elements in the=",a)

the elements in the= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
import numpy as np
a=np.full((4,3),7)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [16]:
import numpy as np
a=np.random.random((4,3))
print(a)

[[0.82030655 0.23511541 0.38165039]
 [0.00361556 0.19993511 0.18809772]
 [0.23769742 0.51107285 0.23906051]
 [0.89874782 0.50387432 0.64849992]]


In [19]:
import numpy as np
a=np.arange(5,30,2)
print(a)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [27]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
b=a.reshape(4,2)
print(b)

[[1 2]
 [3 4]
 [2 3]
 [4 5]]


In [29]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
b=a.flatten()
print(b)

[1 2 3 4 2 3 4 5]


In [31]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
print(a.ndim)

2


In [32]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
print(a.shape)

(2, 4)


In [33]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
print(a.size)

8


In [34]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
print(a.dtype)

int32


In [35]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
b=a.astype('f')
print(b)

[[1. 2. 3. 4.]
 [2. 3. 4. 5.]]


In [39]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
b=a[0:1:1]
print(b)

[[1 2 3 4]]


In [43]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
b=a[0,1:3]
print(b)

[2 3]


In [44]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
b=a[1:,1:]
print(b)

[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [45]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [3]:
import numpy as np
a=np.array([[1,2,3,0],[2,3,4,0],[4,5,6,0]])
b=a.reshape(4,3)
print(b)

[[1 2 3]
 [0 2 3]
 [4 0 4]
 [5 6 0]]


In [10]:
import numpy as nm
a=np.array([[-1,2,3,0],[2,-3,4,0],[4,-5,6,0],[5,4,3,6]])
temp=a[:2,:3]
print(temp)


[[-1  2  3]
 [ 2 -3  4]]


In [12]:
import numpy as nm
a=np.array([[-1,2,3,0],[2,-3,4,0],[4,-5,6,0],[5,4,3,6]])
b=a[[9,9,9,9],[8,8,8,8]]
print(b)

IndexError: index 9 is out of bounds for axis 0 with size 4

In [13]:
import numpy as nm
a=np.array([[-1,2,3,0],[2,-3,4,0],[4,-5,6,0],[5,4,3,6]])
cond=a>2
temp=a[cond]
print(temp)

[3 4 4 6 5 4 3 6]


In [14]:
import numpy as nm
a=np.array([1,2,3,4,5])
print(a[::2])

[1 3 5]


In [15]:
import numpy as nm
a=np.array([[-1,2,3,0],[2,-3,4,0]])
b=np.array([[4,-5,6,0],[5,4,3,6]])
c=np.concatenate((a,b))
print(c)

[[-1  2  3  0]
 [ 2 -3  4  0]
 [ 4 -5  6  0]
 [ 5  4  3  6]]


In [16]:
import numpy as nm
a=np.array([[-1,2,3,0],[2,-3,4,0]])
b=np.array([[4,-5,6,0],[5,4,3,6]])
c=np.hstack((a,b))
print(c)

[[-1  2  3  0  4 -5  6  0]
 [ 2 -3  4  0  5  4  3  6]]


In [4]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.vstack((a,b))
print(c)

[[1 2 3]
 [2 3 4]]


In [5]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.dstack((a,b))
print(c)

[[[1 2]
  [2 3]
  [3 4]]]


In [6]:
import numpy as np
a=np.array([1,2,3])
b=np.array_split(a,2)
print(b)


[array([1, 2]), array([3])]


In [8]:
import numpy as np
a=np.array([1,2,3])
b=np.array_split(a,2)
print(b[0])
print(b[1])

[1 2]
[3]


In [9]:
import numpy as np
a=np.array ([1,2,3,4,5,6])
x=np.where(a==4)
print(x)

(array([3], dtype=int64),)


In [11]:
import numpy as np
a=np.array ([1,2,3,4,5,6])
x=np.where(a%2==0)
print(x)

(array([1, 3, 5], dtype=int64),)


In [12]:
import numpy as np
a=np.array ([1,2,3,4,5,6])
x=np.searchsorted(a,3,side='left')
print(x)

2


In [13]:
import numpy as np
a=np.array ([4,3,2,1])
x=np.sort(a)
print(x)

[1 2 3 4]


In [19]:
import numpy as np
a=np.array ([1,2,3,4])
b=a>2
c=a[b]
print(b)
print(c)

[False False  True  True]
[3 4]


In [22]:
import numpy as np
a1=[10,20,30,40,50]
a2=[2,4,6,8,10]
a=np.array(a1)
b=np.array(a2)
print("vector addition")
print(a+b)
print("\nvector subraction")
print(a-b)

print("\nvector multiplication")
print(a*b)
print("\n vector division")
print(a/b)
print("\nvector dot product")
print(a.dot(b))
print("\nsclar multiplication")
sclr=5
print(" sclar value=",sclr)
print(" array=",a)
print(" result=",a*sclr)



vector addition
[12 24 36 48 60]

vector subraction
[ 8 16 24 32 40]

vector multiplication
[ 20  80 180 320 500]

 vector division
[5. 5. 5. 5. 5.]

vector dot product
1100

sclar multiplication
 sclar value= 5
 array= [10 20 30 40 50]
 result= [ 50 100 150 200 250]


In [27]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
    print("\n\n numpy.vectorize methord")
    print("(return x-y if x>y,otherwise return x+y)")
    a=[10,4,20]
    b=[2,3,30]
    vec_func=numpy.vectorize(my_func)
    print("array1:",a)
    print("array2:",b)
    print("result:",vec_func(a,b))
        
    